(define (make-account balance pw)
	(define (withdraw amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
				balance)
			"Insufficient funds"))
	(define (deposit amount)
		(set! balance (+ balance amount))
		balance)
	(define (dispatch m)
		(cond ((eq? m 'withdraw) withdraw)
			  ((eq? m 'deposit) deposit)
			  (else (error "Unknown request -- MAKE-ACCOUNT") m)))
	(define (wrap-pw pass msg)
		(if (eq? pass pw) (dispatch msg)
			(error "Incorrect password")))
wrap-pw)

;(define w (make-account 100))
;((w 'withdraw) 50)

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)

((acc 'some-other-password 'deposit) 50)
